# Generated by Django 4.0.5 on 2022-08-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Magazines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magazine_name', models.CharField(max_length=50)),
                ('published_at', models.DateField()),
                ('magazine_copy', models.FileField(upload_to='upload/')),
            ],
        ),
    ]
