# Generated by Django 4.0.5 on 2022-08-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Magazine', '0003_myclubuser_magazines_attendees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magazines',
            name='attendees',
        ),
        migrations.AddField(
            model_name='magazines',
            name='uploaded_by',
            field=models.ManyToManyField(blank=True, null=True, to='Magazine.myclubuser'),
        ),
    ]
