# Generated by Django 4.0.5 on 2022-08-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Magazine', '0004_remove_magazines_attendees_magazines_uploaded_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magazines',
            name='uploaded_by',
        ),
        migrations.AlterField(
            model_name='magazines',
            name='magazine_copy',
            field=models.FileField(blank=True, upload_to='upload/', verbose_name='Magazine_Copy'),
        ),
        migrations.AlterField(
            model_name='magazines',
            name='magazine_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Magazine_Name'),
        ),
        migrations.AlterField(
            model_name='magazines',
            name='published_at',
            field=models.DateField(blank=True),
        ),
    ]
