# Generated by Django 4.0.5 on 2022-08-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Magazine', '0005_remove_magazines_uploaded_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazines',
            name='uploaded_by',
            field=models.ManyToManyField(blank=True, null=True, to='Magazine.myclubuser'),
        ),
        migrations.AlterField(
            model_name='magazines',
            name='magazine_copy',
            field=models.FileField(blank=True, null=True, upload_to='upload/', verbose_name='Magazine_Copy'),
        ),
    ]
